server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod        











#person: 
#  lastName: hello
#  age: 18
#  birth: 2017/12/12
#  map: {k1: v1,k2: v2}
#  list: 
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小黑
#    age: 12 